# Generated by Django 2.2.2 on 2019-06-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='circle descirption')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='verified circles are also known as official communities', verbose_name='verified circle')),
                ('is_public', models.BooleanField(default=True, help_text='Publick circles are listed in main page, everyone knows about their existance.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to a limited number of members.', verbose_name='limited')),
                ('numbers_limit', models.IntegerField(default=0, help_text='if circle is limited, this will be the number of users con be added')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
