# Generated by Django 2.2.2 on 2019-06-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circles',
            new_name='Circle',
        ),
    ]
